import type { CustomerUser, CustomerOrderHistory, CustomerWalletTransaction } from "@/types";

const now = new Date();
function daysAgo(days: number): string {
  return new Date(now.getTime() - days * 86400000).toISOString();
}
function hoursAgo(hours: number): string {
  return new Date(now.getTime() - hours * 3600000).toISOString();
}

export const MOCK_CUSTOMERS: CustomerUser[] = [
  {
    id: "cust-001",
    name: "Chioma Okeke",
    email: "chioma.okeke@gmail.com",
    phone: "+234 812 345 6789",
    accountStatus: "active",
    joinedAt: "2025-03-15T10:00:00Z",
    lastActiveAt: hoursAgo(1),
    totalOrders: 47,
    totalSpent: 185600,
    walletBalance: 3200,
    isFraudFlagged: false,
    addresses: [
      { id: "addr-001", label: "Home", address: "12 Admiralty Way, Lekki Phase 1, Lagos", isDefault: true },
      { id: "addr-002", label: "Office", address: "25 Adeola Odeku St, Victoria Island, Lagos", isDefault: false },
    ],
    tags: ["frequent", "premium"],
  },
  {
    id: "cust-002",
    name: "Emeka Chukwu",
    email: "emeka.chukwu@yahoo.com",
    phone: "+234 803 456 7890",
    accountStatus: "active",
    joinedAt: "2025-05-20T14:00:00Z",
    lastActiveAt: hoursAgo(3),
    totalOrders: 23,
    totalSpent: 89400,
    walletBalance: 1500,
    isFraudFlagged: false,
    addresses: [
      { id: "addr-003", label: "Home", address: "8 Allen Avenue, Ikeja, Lagos", isDefault: true },
    ],
    tags: ["regular"],
  },
  {
    id: "cust-003",
    name: "Amara Nwosu",
    email: "amara.nwosu@outlook.com",
    phone: "+234 815 678 9012",
    accountStatus: "active",
    joinedAt: "2025-01-10T09:00:00Z",
    lastActiveAt: hoursAgo(5),
    totalOrders: 62,
    totalSpent: 248000,
    walletBalance: 5400,
    isFraudFlagged: false,
    addresses: [
      { id: "addr-004", label: "Home", address: "3 Ozumba Mbadiwe Ave, Victoria Island, Lagos", isDefault: true },
      { id: "addr-005", label: "Gym", address: "15 Awolowo Rd, Ikoyi, Lagos", isDefault: false },
    ],
    tags: ["frequent", "premium", "early_adopter"],
  },
  {
    id: "cust-004",
    name: "Tunde Bakare",
    email: "tunde.b@gmail.com",
    phone: "+234 807 890 1234",
    accountStatus: "suspended",
    joinedAt: "2025-06-01T11:00:00Z",
    lastActiveAt: daysAgo(5),
    totalOrders: 8,
    totalSpent: 32000,
    walletBalance: 0,
    isFraudFlagged: true,
    fraudFlagReason: "Multiple chargebacks on card payments",
    addresses: [
      { id: "addr-006", label: "Home", address: "22 Ogunlana Dr, Surulere, Lagos", isDefault: true },
    ],
    tags: ["flagged"],
  },
  {
    id: "cust-005",
    name: "Ngozi Eze",
    email: "ngozi.eze@gmail.com",
    phone: "+234 810 123 4567",
    accountStatus: "active",
    joinedAt: "2025-04-22T16:00:00Z",
    lastActiveAt: hoursAgo(8),
    totalOrders: 35,
    totalSpent: 142000,
    walletBalance: 2800,
    isFraudFlagged: false,
    addresses: [
      { id: "addr-007", label: "Home", address: "5 Akin Adesola St, Victoria Island, Lagos", isDefault: true },
    ],
    tags: ["regular"],
  },
  {
    id: "cust-006",
    name: "Oluwaseun Adeyemi",
    email: "seun.adeyemi@hotmail.com",
    phone: "+234 802 234 5678",
    accountStatus: "active",
    joinedAt: "2025-07-05T08:00:00Z",
    lastActiveAt: hoursAgo(2),
    totalOrders: 18,
    totalSpent: 71200,
    walletBalance: 1000,
    isFraudFlagged: false,
    addresses: [
      { id: "addr-008", label: "Home", address: "14 Bode Thomas St, Surulere, Lagos", isDefault: true },
      { id: "addr-009", label: "Work", address: "7 Broad St, Lagos Island, Lagos", isDefault: false },
    ],
    tags: ["regular"],
  },
  {
    id: "cust-007",
    name: "Fatima Abdullahi",
    email: "fatima.a@gmail.com",
    phone: "+234 816 345 6789",
    accountStatus: "active",
    joinedAt: "2025-02-14T12:00:00Z",
    lastActiveAt: hoursAgo(12),
    totalOrders: 54,
    totalSpent: 216000,
    walletBalance: 4200,
    isFraudFlagged: false,
    addresses: [
      { id: "addr-010", label: "Home", address: "9 Adetokunbo Ademola St, Wuse 2, Abuja", isDefault: true },
    ],
    tags: ["frequent", "premium"],
  },
  {
    id: "cust-008",
    name: "Ikechukwu Obi",
    email: "ike.obi@gmail.com",
    phone: "+234 805 456 7890",
    accountStatus: "banned",
    joinedAt: "2025-08-10T15:00:00Z",
    lastActiveAt: daysAgo(14),
    totalOrders: 3,
    totalSpent: 8500,
    walletBalance: 0,
    isFraudFlagged: true,
    fraudFlagReason: "Fake account — multiple fraud attempts with stolen cards",
    addresses: [
      { id: "addr-011", label: "Home", address: "Unknown address", isDefault: true },
    ],
    tags: ["banned", "fraud"],
  },
  {
    id: "cust-009",
    name: "Aisha Mohammed",
    email: "aisha.m@yahoo.com",
    phone: "+234 811 567 8901",
    accountStatus: "active",
    joinedAt: "2025-05-30T10:00:00Z",
    lastActiveAt: hoursAgo(6),
    totalOrders: 29,
    totalSpent: 115600,
    walletBalance: 1800,
    isFraudFlagged: false,
    addresses: [
      { id: "addr-012", label: "Home", address: "18 Herbert Macaulay Way, Yaba, Lagos", isDefault: true },
    ],
    tags: ["regular"],
  },
  {
    id: "cust-010",
    name: "Daniel Okonkwo",
    email: "daniel.okonkwo@gmail.com",
    phone: "+234 809 678 9012",
    accountStatus: "active",
    joinedAt: "2025-04-01T09:00:00Z",
    lastActiveAt: hoursAgo(4),
    totalOrders: 41,
    totalSpent: 164800,
    walletBalance: 3600,
    isFraudFlagged: false,
    addresses: [
      { id: "addr-013", label: "Home", address: "6 Ligali Ayorinde St, Victoria Island, Lagos", isDefault: true },
      { id: "addr-014", label: "Parents", address: "31 Awka Rd, Onitsha, Anambra", isDefault: false },
    ],
    tags: ["frequent"],
  },
  {
    id: "cust-011",
    name: "Blessing Okafor",
    email: "blessing.okafor@gmail.com",
    phone: "+234 814 789 0123",
    accountStatus: "active",
    joinedAt: "2025-06-18T14:00:00Z",
    lastActiveAt: hoursAgo(10),
    totalOrders: 16,
    totalSpent: 64000,
    walletBalance: 800,
    isFraudFlagged: false,
    addresses: [
      { id: "addr-015", label: "Home", address: "20 Oba Akran Ave, Ikeja, Lagos", isDefault: true },
    ],
    tags: ["new"],
  },
  {
    id: "cust-012",
    name: "Yusuf Ibrahim",
    email: "yusuf.ibrahim@gmail.com",
    phone: "+234 806 890 1234",
    accountStatus: "deactivated",
    joinedAt: "2025-03-25T11:00:00Z",
    lastActiveAt: daysAgo(30),
    totalOrders: 12,
    totalSpent: 48000,
    walletBalance: 0,
    isFraudFlagged: false,
    addresses: [
      { id: "addr-016", label: "Home", address: "4 Ahmadu Bello Way, Kaduna", isDefault: true },
    ],
    tags: [],
  },
  {
    id: "cust-013",
    name: "Adaeze Nnamdi",
    email: "adaeze.n@outlook.com",
    phone: "+234 813 901 2345",
    accountStatus: "active",
    joinedAt: "2025-07-22T09:00:00Z",
    lastActiveAt: hoursAgo(1),
    totalOrders: 11,
    totalSpent: 44800,
    walletBalance: 1200,
    isFraudFlagged: false,
    addresses: [
      { id: "addr-017", label: "Home", address: "11 Kofo Abayomi St, Victoria Island, Lagos", isDefault: true },
    ],
    tags: ["new"],
  },
  {
    id: "cust-014",
    name: "Olumide Falade",
    email: "olumide.f@gmail.com",
    phone: "+234 808 012 3456",
    accountStatus: "active",
    joinedAt: "2025-01-05T13:00:00Z",
    lastActiveAt: hoursAgo(7),
    totalOrders: 78,
    totalSpent: 312000,
    walletBalance: 8500,
    isFraudFlagged: false,
    addresses: [
      { id: "addr-018", label: "Home", address: "16 Sanusi Fafunwa St, Victoria Island, Lagos", isDefault: true },
      { id: "addr-019", label: "Office", address: "2 Idowu Taylor St, Victoria Island, Lagos", isDefault: false },
    ],
    tags: ["frequent", "premium", "vip"],
  },
  {
    id: "cust-015",
    name: "Funke Adebanjo",
    email: "funke.a@gmail.com",
    phone: "+234 817 123 4567",
    accountStatus: "active",
    joinedAt: "2025-08-01T10:00:00Z",
    lastActiveAt: hoursAgo(15),
    totalOrders: 7,
    totalSpent: 28000,
    walletBalance: 500,
    isFraudFlagged: false,
    addresses: [
      { id: "addr-020", label: "Home", address: "8 Lekki-Epe Expressway, Ajah, Lagos", isDefault: true },
    ],
    tags: ["new"],
  },
  {
    id: "cust-016",
    name: "Chidi Nwankwo",
    email: "chidi.n@yahoo.com",
    phone: "+234 804 234 5678",
    accountStatus: "suspended",
    joinedAt: "2025-05-12T16:00:00Z",
    lastActiveAt: daysAgo(3),
    totalOrders: 14,
    totalSpent: 56000,
    walletBalance: 200,
    isFraudFlagged: true,
    fraudFlagReason: "Excessive refund requests — suspected abuse",
    addresses: [
      { id: "addr-021", label: "Home", address: "19 Toyin St, Ikeja, Lagos", isDefault: true },
    ],
    tags: ["flagged"],
  },
  {
    id: "cust-017",
    name: "Kemi Oladipo",
    email: "kemi.oladipo@gmail.com",
    phone: "+234 818 345 6789",
    accountStatus: "active",
    joinedAt: "2025-02-28T08:00:00Z",
    lastActiveAt: hoursAgo(2),
    totalOrders: 44,
    totalSpent: 176000,
    walletBalance: 3000,
    isFraudFlagged: false,
    addresses: [
      { id: "addr-022", label: "Home", address: "7 Glover Rd, Ikoyi, Lagos", isDefault: true },
    ],
    tags: ["frequent", "premium"],
  },
  {
    id: "cust-018",
    name: "Obinna Agu",
    email: "obinna.agu@gmail.com",
    phone: "+234 801 456 7890",
    accountStatus: "active",
    joinedAt: "2025-06-25T12:00:00Z",
    lastActiveAt: hoursAgo(9),
    totalOrders: 19,
    totalSpent: 76000,
    walletBalance: 1400,
    isFraudFlagged: false,
    addresses: [
      { id: "addr-023", label: "Home", address: "23 Adetola St, Aguda, Surulere, Lagos", isDefault: true },
    ],
    tags: ["regular"],
  },
  {
    id: "cust-019",
    name: "Halima Bello",
    email: "halima.bello@gmail.com",
    phone: "+234 819 567 8901",
    accountStatus: "active",
    joinedAt: "2025-04-10T15:00:00Z",
    lastActiveAt: hoursAgo(4),
    totalOrders: 33,
    totalSpent: 132000,
    walletBalance: 2600,
    isFraudFlagged: false,
    addresses: [
      { id: "addr-024", label: "Home", address: "10 Maitama Sule St, Asokoro, Abuja", isDefault: true },
      { id: "addr-025", label: "Office", address: "1 Shehu Shagari Way, CBD, Abuja", isDefault: false },
    ],
    tags: ["frequent"],
  },
  {
    id: "cust-020",
    name: "Solomon Adegoke",
    email: "solomon.a@outlook.com",
    phone: "+234 807 678 9012",
    accountStatus: "active",
    joinedAt: "2025-07-15T11:00:00Z",
    lastActiveAt: hoursAgo(6),
    totalOrders: 9,
    totalSpent: 36000,
    walletBalance: 700,
    isFraudFlagged: false,
    addresses: [
      { id: "addr-026", label: "Home", address: "15 Ikorodu Rd, Maryland, Lagos", isDefault: true },
    ],
    tags: ["new"],
  },
];

export const MOCK_CUSTOMER_ORDER_HISTORY: Record<string, CustomerOrderHistory[]> = {
  "cust-001": [
    { orderId: "ord-3420", orderNumber: "#3420", vendorName: "Chicken Republic", total: 4500, status: "delivered", placedAt: hoursAgo(3) },
    { orderId: "ord-3398", orderNumber: "#3398", vendorName: "Kilimanjaro", total: 6200, status: "delivered", placedAt: daysAgo(1) },
    { orderId: "ord-3370", orderNumber: "#3370", vendorName: "The Place", total: 3800, status: "delivered", placedAt: daysAgo(3) },
    { orderId: "ord-3345", orderNumber: "#3345", vendorName: "Domino's Pizza", total: 8900, status: "delivered", placedAt: daysAgo(5) },
    { orderId: "ord-3310", orderNumber: "#3310", vendorName: "Sweet Sensation", total: 2400, status: "cancelled", placedAt: daysAgo(7) },
  ],
  "cust-003": [
    { orderId: "ord-3422", orderNumber: "#3422", vendorName: "Bukka Hut", total: 5600, status: "on_the_way", placedAt: hoursAgo(1) },
    { orderId: "ord-3400", orderNumber: "#3400", vendorName: "Kilimanjaro", total: 7200, status: "delivered", placedAt: daysAgo(1) },
    { orderId: "ord-3380", orderNumber: "#3380", vendorName: "Tantalizers", total: 3200, status: "delivered", placedAt: daysAgo(2) },
  ],
  "cust-014": [
    { orderId: "ord-3419", orderNumber: "#3419", vendorName: "Domino's Pizza", total: 12500, status: "delivered", placedAt: hoursAgo(5) },
    { orderId: "ord-3405", orderNumber: "#3405", vendorName: "Chicken Republic", total: 5800, status: "delivered", placedAt: daysAgo(1) },
    { orderId: "ord-3390", orderNumber: "#3390", vendorName: "Bukka Hut", total: 4200, status: "delivered", placedAt: daysAgo(2) },
    { orderId: "ord-3365", orderNumber: "#3365", vendorName: "KFC Nigeria", total: 7600, status: "delivered", placedAt: daysAgo(4) },
  ],
};

export const MOCK_CUSTOMER_WALLET_TRANSACTIONS: Record<string, CustomerWalletTransaction[]> = {
  "cust-001": [
    { id: "wtx-001", type: "credit", amount: 2000, description: "Refund — Order #3310 cancelled", timestamp: daysAgo(7), balanceAfter: 3200 },
    { id: "wtx-002", type: "credit", amount: 1500, description: "Promo credit — Welcome back offer", timestamp: daysAgo(10), balanceAfter: 1200 },
    { id: "wtx-003", type: "debit", amount: 300, description: "Wallet payment — Order #3370", timestamp: daysAgo(3), balanceAfter: 3500 },
  ],
  "cust-003": [
    { id: "wtx-004", type: "credit", amount: 5000, description: "Top up via card", timestamp: daysAgo(2), balanceAfter: 5400 },
    { id: "wtx-005", type: "debit", amount: 1200, description: "Wallet payment — Order #3380", timestamp: daysAgo(2), balanceAfter: 400 },
    { id: "wtx-006", type: "credit", amount: 1000, description: "Referral bonus — Emeka Chukwu signed up", timestamp: daysAgo(5), balanceAfter: 1600 },
  ],
  "cust-014": [
    { id: "wtx-007", type: "credit", amount: 10000, description: "Top up via bank transfer", timestamp: daysAgo(1), balanceAfter: 8500 },
    { id: "wtx-008", type: "debit", amount: 2500, description: "Wallet payment — Order #3419", timestamp: hoursAgo(5), balanceAfter: 8500 },
    { id: "wtx-009", type: "credit", amount: 500, description: "Loyalty points conversion", timestamp: daysAgo(3), balanceAfter: 11000 },
    { id: "wtx-010", type: "debit", amount: 1000, description: "Wallet payment — Order #3405", timestamp: daysAgo(1), balanceAfter: 10500 },
  ],
};
