import type { AdminOrder, AdminOrderTimelineEvent, OrderDispute } from "@/types";

const now = new Date();
function minutesAgo(minutes: number): string {
  return new Date(now.getTime() - minutes * 60000).toISOString();
}
function hoursAgo(hours: number): string {
  return new Date(now.getTime() - hours * 3600000).toISOString();
}
function daysAgo(days: number): string {
  return new Date(now.getTime() - days * 86400000).toISOString();
}

export const MOCK_ADMIN_ORDERS: AdminOrder[] = [
  {
    id: "aord-001", orderNumber: "#3422", status: "on_the_way", priority: "normal",
    customerName: "Amara Nwosu", customerId: "cust-003",
    vendorName: "Bukka Hut", vendorId: "vend-001",
    riderName: "Chinedu Eze", riderId: "rider-005",
    items: [
      { id: "item-001", name: "Jollof Rice & Chicken", quantity: 2, unitPrice: 2200 },
      { id: "item-002", name: "Moi Moi", quantity: 1, unitPrice: 800 },
    ],
    subtotal: 5200, deliveryFee: 500, serviceFee: 200, discount: 300, total: 5600,
    paymentMethod: "card", paymentStatus: "paid",
    deliveryAddress: "3 Ozumba Mbadiwe Ave, Victoria Island, Lagos",
    placedAt: hoursAgo(1), confirmedAt: minutesAgo(50), prepStartedAt: minutesAgo(45), readyAt: minutesAgo(20), pickedUpAt: minutesAgo(15),
    isDisputed: false,
  },
  {
    id: "aord-002", orderNumber: "#3421", status: "disputed", priority: "urgent",
    customerName: "Chioma Okeke", customerId: "cust-001",
    vendorName: "Chicken Republic", vendorId: "vend-002",
    riderName: "Adamu Sani", riderId: "rider-003",
    items: [
      { id: "item-003", name: "Chicken Meal Box", quantity: 1, unitPrice: 3200 },
      { id: "item-004", name: "Coleslaw", quantity: 1, unitPrice: 500 },
    ],
    subtotal: 3700, deliveryFee: 400, serviceFee: 150, discount: 0, total: 4250,
    paymentMethod: "card", paymentStatus: "paid",
    deliveryAddress: "12 Admiralty Way, Lekki Phase 1, Lagos",
    placedAt: hoursAgo(3), confirmedAt: hoursAgo(2.8), prepStartedAt: hoursAgo(2.5), readyAt: hoursAgo(2), pickedUpAt: hoursAgo(1.8), deliveredAt: hoursAgo(1.5),
    isDisputed: true, disputeReason: "Duplicate payment detected",
    adminNotes: "Payment gateway charged customer twice. Investigating with Paystack.",
  },
  {
    id: "aord-003", orderNumber: "#3420", status: "delivered", priority: "normal",
    customerName: "Chioma Okeke", customerId: "cust-001",
    vendorName: "Chicken Republic", vendorId: "vend-002",
    items: [
      { id: "item-005", name: "Spicy Chicken Wings (6pc)", quantity: 1, unitPrice: 2800 },
      { id: "item-006", name: "Fried Rice", quantity: 1, unitPrice: 1700 },
    ],
    subtotal: 4500, deliveryFee: 400, serviceFee: 150, discount: 550, total: 4500,
    paymentMethod: "wallet", paymentStatus: "paid",
    deliveryAddress: "12 Admiralty Way, Lekki Phase 1, Lagos",
    placedAt: hoursAgo(4), confirmedAt: hoursAgo(3.8), prepStartedAt: hoursAgo(3.5), readyAt: hoursAgo(3), pickedUpAt: hoursAgo(2.8), deliveredAt: hoursAgo(2.5),
    isDisputed: false,
  },
  {
    id: "aord-004", orderNumber: "#3419", status: "delivered", priority: "normal",
    customerName: "Olumide Falade", customerId: "cust-014",
    vendorName: "Domino's Pizza", vendorId: "vend-003",
    riderName: "Tolu Ajayi", riderId: "rider-007",
    items: [
      { id: "item-007", name: "Pepperoni Pizza (Large)", quantity: 1, unitPrice: 8500 },
      { id: "item-008", name: "Garlic Bread", quantity: 1, unitPrice: 2000 },
      { id: "item-009", name: "Coke (50cl)", quantity: 2, unitPrice: 500 },
    ],
    subtotal: 11500, deliveryFee: 600, serviceFee: 400, discount: 0, total: 12500,
    paymentMethod: "card", paymentStatus: "paid",
    deliveryAddress: "16 Sanusi Fafunwa St, Victoria Island, Lagos",
    placedAt: hoursAgo(5), confirmedAt: hoursAgo(4.8), prepStartedAt: hoursAgo(4.5), readyAt: hoursAgo(4), pickedUpAt: hoursAgo(3.8), deliveredAt: hoursAgo(3.5),
    isDisputed: false,
  },
  {
    id: "aord-005", orderNumber: "#3418", status: "preparing", priority: "urgent",
    customerName: "Kemi Oladipo", customerId: "cust-017",
    vendorName: "Kilimanjaro", vendorId: "vend-004",
    items: [
      { id: "item-010", name: "Suya Platter", quantity: 1, unitPrice: 4500 },
      { id: "item-011", name: "Chapman", quantity: 2, unitPrice: 1200 },
    ],
    subtotal: 6900, deliveryFee: 500, serviceFee: 250, discount: 0, total: 7650,
    paymentMethod: "transfer", paymentStatus: "paid",
    deliveryAddress: "7 Glover Rd, Ikoyi, Lagos",
    specialInstructions: "Extra spicy suya please",
    placedAt: minutesAgo(45), confirmedAt: minutesAgo(40), prepStartedAt: minutesAgo(35),
    isDisputed: false,
    adminNotes: "Customer waiting 45+ min — escalated to urgent",
  },
  {
    id: "aord-006", orderNumber: "#3417", status: "cancelled", priority: "normal",
    customerName: "Daniel Okonkwo", customerId: "cust-010",
    vendorName: "Sweet Sensation", vendorId: "vend-005",
    items: [
      { id: "item-012", name: "Meat Pie (2pc)", quantity: 2, unitPrice: 800 },
      { id: "item-013", name: "Scotch Egg", quantity: 1, unitPrice: 600 },
    ],
    subtotal: 2200, deliveryFee: 350, serviceFee: 100, discount: 0, total: 2650,
    paymentMethod: "card", paymentStatus: "refunded",
    deliveryAddress: "6 Ligali Ayorinde St, Victoria Island, Lagos",
    placedAt: hoursAgo(6), confirmedAt: hoursAgo(5.8), cancelledAt: hoursAgo(5.5),
    cancelReason: "Vendor could not fulfill — out of stock",
    isDisputed: false,
  },
  {
    id: "aord-007", orderNumber: "#3416", status: "pending", priority: "normal",
    customerName: "Obinna Agu", customerId: "cust-018",
    vendorName: "Tantalizers", vendorId: "vend-006",
    items: [
      { id: "item-014", name: "Sharwarma (Large)", quantity: 1, unitPrice: 3500 },
      { id: "item-015", name: "Fanta (50cl)", quantity: 1, unitPrice: 400 },
    ],
    subtotal: 3900, deliveryFee: 400, serviceFee: 150, discount: 0, total: 4450,
    paymentMethod: "cash", paymentStatus: "pending",
    deliveryAddress: "23 Adetola St, Aguda, Surulere, Lagos",
    placedAt: minutesAgo(5),
    isDisputed: false,
  },
  {
    id: "aord-008", orderNumber: "#3415", status: "disputed", priority: "high",
    customerName: "Aisha Mohammed", customerId: "cust-009",
    vendorName: "The Place", vendorId: "vend-007",
    riderName: "Musa Bello", riderId: "rider-010",
    items: [
      { id: "item-016", name: "Amala & Ewedu", quantity: 1, unitPrice: 2000 },
      { id: "item-017", name: "Assorted Meat", quantity: 1, unitPrice: 1500 },
    ],
    subtotal: 3500, deliveryFee: 450, serviceFee: 150, discount: 0, total: 4100,
    paymentMethod: "card", paymentStatus: "paid",
    deliveryAddress: "18 Herbert Macaulay Way, Yaba, Lagos",
    placedAt: hoursAgo(8), confirmedAt: hoursAgo(7.8), prepStartedAt: hoursAgo(7.5), readyAt: hoursAgo(7), pickedUpAt: hoursAgo(6.8), deliveredAt: hoursAgo(6.5),
    isDisputed: true, disputeReason: "Wrong items delivered",
    adminNotes: "Customer received amala & gbegiri instead of ewedu. Vendor confirmed mix-up.",
  },
  {
    id: "aord-009", orderNumber: "#3414", status: "confirmed", priority: "normal",
    customerName: "Halima Bello", customerId: "cust-019",
    vendorName: "Bukka Hut", vendorId: "vend-001",
    items: [
      { id: "item-018", name: "Fried Rice & Plantain", quantity: 1, unitPrice: 2500 },
      { id: "item-019", name: "Grilled Fish", quantity: 1, unitPrice: 3200 },
    ],
    subtotal: 5700, deliveryFee: 500, serviceFee: 200, discount: 400, total: 6000,
    paymentMethod: "card", paymentStatus: "paid",
    deliveryAddress: "10 Maitama Sule St, Asokoro, Abuja",
    placedAt: minutesAgo(12), confirmedAt: minutesAgo(8),
    isDisputed: false,
  },
  {
    id: "aord-010", orderNumber: "#3413", status: "ready", priority: "high",
    customerName: "Emeka Chukwu", customerId: "cust-002",
    vendorName: "KFC Nigeria", vendorId: "vend-008",
    items: [
      { id: "item-020", name: "Zinger Burger Meal", quantity: 2, unitPrice: 3800 },
    ],
    subtotal: 7600, deliveryFee: 500, serviceFee: 300, discount: 0, total: 8400,
    paymentMethod: "card", paymentStatus: "paid",
    deliveryAddress: "8 Allen Avenue, Ikeja, Lagos",
    placedAt: minutesAgo(30), confirmedAt: minutesAgo(25), prepStartedAt: minutesAgo(20), readyAt: minutesAgo(5),
    isDisputed: false,
    adminNotes: "No rider assigned yet — Ikeja zone has limited availability",
  },
  {
    id: "aord-011", orderNumber: "#3412", status: "picked_up", priority: "normal",
    customerName: "Ngozi Eze", customerId: "cust-005",
    vendorName: "Chicken Republic", vendorId: "vend-002",
    riderName: "Ibrahim Yusuf", riderId: "rider-012",
    items: [
      { id: "item-021", name: "Chicken & Chips", quantity: 1, unitPrice: 2800 },
      { id: "item-022", name: "Ice Cream", quantity: 1, unitPrice: 600 },
    ],
    subtotal: 3400, deliveryFee: 400, serviceFee: 150, discount: 0, total: 3950,
    paymentMethod: "wallet", paymentStatus: "paid",
    deliveryAddress: "5 Akin Adesola St, Victoria Island, Lagos",
    placedAt: minutesAgo(40), confirmedAt: minutesAgo(35), prepStartedAt: minutesAgo(30), readyAt: minutesAgo(15), pickedUpAt: minutesAgo(10),
    isDisputed: false,
  },
  {
    id: "aord-012", orderNumber: "#3411", status: "delivered", priority: "normal",
    customerName: "Fatima Abdullahi", customerId: "cust-007",
    vendorName: "Kilimanjaro", vendorId: "vend-004",
    riderName: "Ahmed Lawal", riderId: "rider-015",
    items: [
      { id: "item-023", name: "Pepper Soup", quantity: 1, unitPrice: 3000 },
      { id: "item-024", name: "Pounded Yam", quantity: 1, unitPrice: 1500 },
    ],
    subtotal: 4500, deliveryFee: 600, serviceFee: 200, discount: 0, total: 5300,
    paymentMethod: "transfer", paymentStatus: "paid",
    deliveryAddress: "9 Adetokunbo Ademola St, Wuse 2, Abuja",
    placedAt: hoursAgo(10), confirmedAt: hoursAgo(9.8), prepStartedAt: hoursAgo(9.5), readyAt: hoursAgo(9), pickedUpAt: hoursAgo(8.8), deliveredAt: hoursAgo(8.5),
    isDisputed: false,
  },
  {
    id: "aord-013", orderNumber: "#3410", status: "refunded", priority: "normal",
    customerName: "Solomon Adegoke", customerId: "cust-020",
    vendorName: "Sweet Sensation", vendorId: "vend-005",
    items: [
      { id: "item-025", name: "Chicken Pie", quantity: 3, unitPrice: 500 },
      { id: "item-026", name: "Doughnut", quantity: 2, unitPrice: 300 },
    ],
    subtotal: 2100, deliveryFee: 350, serviceFee: 100, discount: 0, total: 2550,
    paymentMethod: "card", paymentStatus: "refunded",
    deliveryAddress: "15 Ikorodu Rd, Maryland, Lagos",
    placedAt: daysAgo(1), confirmedAt: daysAgo(1), cancelledAt: daysAgo(1),
    cancelReason: "Rider never arrived — full refund issued",
    isDisputed: false,
  },
  {
    id: "aord-014", orderNumber: "#3409", status: "delivered", priority: "normal",
    customerName: "Blessing Okafor", customerId: "cust-011",
    vendorName: "Domino's Pizza", vendorId: "vend-003",
    riderName: "Chinedu Eze", riderId: "rider-005",
    items: [
      { id: "item-027", name: "Margherita Pizza (Medium)", quantity: 1, unitPrice: 5500 },
    ],
    subtotal: 5500, deliveryFee: 500, serviceFee: 200, discount: 500, total: 5700,
    paymentMethod: "card", paymentStatus: "paid",
    deliveryAddress: "20 Oba Akran Ave, Ikeja, Lagos",
    placedAt: daysAgo(1), confirmedAt: daysAgo(1), prepStartedAt: daysAgo(1), readyAt: daysAgo(1), pickedUpAt: daysAgo(1), deliveredAt: daysAgo(1),
    isDisputed: false,
  },
  {
    id: "aord-015", orderNumber: "#3408", status: "delivered", priority: "normal",
    customerName: "Adaeze Nnamdi", customerId: "cust-013",
    vendorName: "Tantalizers", vendorId: "vend-006",
    riderName: "Tolu Ajayi", riderId: "rider-007",
    items: [
      { id: "item-028", name: "Spring Rolls (6pc)", quantity: 1, unitPrice: 1800 },
      { id: "item-029", name: "Chicken Sharwarma", quantity: 1, unitPrice: 2500 },
    ],
    subtotal: 4300, deliveryFee: 400, serviceFee: 150, discount: 0, total: 4850,
    paymentMethod: "card", paymentStatus: "paid",
    deliveryAddress: "11 Kofo Abayomi St, Victoria Island, Lagos",
    placedAt: daysAgo(1), confirmedAt: daysAgo(1), prepStartedAt: daysAgo(1), readyAt: daysAgo(1), pickedUpAt: daysAgo(1), deliveredAt: daysAgo(1),
    isDisputed: false,
  },
  {
    id: "aord-016", orderNumber: "#3407", status: "pending", priority: "normal",
    customerName: "Funke Adebanjo", customerId: "cust-015",
    vendorName: "Bukka Hut", vendorId: "vend-001",
    items: [
      { id: "item-030", name: "Egusi Soup & Pounded Yam", quantity: 1, unitPrice: 2800 },
    ],
    subtotal: 2800, deliveryFee: 500, serviceFee: 150, discount: 0, total: 3450,
    paymentMethod: "transfer", paymentStatus: "pending",
    deliveryAddress: "8 Lekki-Epe Expressway, Ajah, Lagos",
    placedAt: minutesAgo(3),
    isDisputed: false,
  },
  {
    id: "aord-017", orderNumber: "#3406", status: "preparing", priority: "normal",
    customerName: "Oluwaseun Adeyemi", customerId: "cust-006",
    vendorName: "The Place", vendorId: "vend-007",
    items: [
      { id: "item-031", name: "Ofada Rice & Stew", quantity: 1, unitPrice: 2200 },
      { id: "item-032", name: "Turkey", quantity: 1, unitPrice: 1800 },
    ],
    subtotal: 4000, deliveryFee: 400, serviceFee: 150, discount: 0, total: 4550,
    paymentMethod: "card", paymentStatus: "paid",
    deliveryAddress: "14 Bode Thomas St, Surulere, Lagos",
    placedAt: minutesAgo(20), confirmedAt: minutesAgo(15), prepStartedAt: minutesAgo(10),
    isDisputed: false,
  },
  {
    id: "aord-018", orderNumber: "#3405", status: "delivered", priority: "normal",
    customerName: "Olumide Falade", customerId: "cust-014",
    vendorName: "Chicken Republic", vendorId: "vend-002",
    riderName: "Ibrahim Yusuf", riderId: "rider-012",
    items: [
      { id: "item-033", name: "Crunchy Chicken Box", quantity: 1, unitPrice: 3500 },
      { id: "item-034", name: "Plantain", quantity: 1, unitPrice: 500 },
      { id: "item-035", name: "Pepsi (50cl)", quantity: 1, unitPrice: 400 },
    ],
    subtotal: 4400, deliveryFee: 400, serviceFee: 150, discount: 0, total: 4950,
    paymentMethod: "wallet", paymentStatus: "paid",
    deliveryAddress: "16 Sanusi Fafunwa St, Victoria Island, Lagos",
    placedAt: daysAgo(1), confirmedAt: daysAgo(1), prepStartedAt: daysAgo(1), readyAt: daysAgo(1), pickedUpAt: daysAgo(1), deliveredAt: daysAgo(1),
    isDisputed: false,
  },
  {
    id: "aord-019", orderNumber: "#3404", status: "cancelled", priority: "normal",
    customerName: "Yusuf Ibrahim", customerId: "cust-012",
    vendorName: "KFC Nigeria", vendorId: "vend-008",
    items: [
      { id: "item-036", name: "Family Bucket", quantity: 1, unitPrice: 9500 },
    ],
    subtotal: 9500, deliveryFee: 600, serviceFee: 350, discount: 0, total: 10450,
    paymentMethod: "card", paymentStatus: "refunded",
    deliveryAddress: "4 Ahmadu Bello Way, Kaduna",
    placedAt: daysAgo(2), cancelledAt: daysAgo(2),
    cancelReason: "Customer requested cancellation — changed mind",
    isDisputed: false,
  },
  {
    id: "aord-020", orderNumber: "#3403", status: "delivered", priority: "normal",
    customerName: "Kemi Oladipo", customerId: "cust-017",
    vendorName: "Bukka Hut", vendorId: "vend-001",
    riderName: "Musa Bello", riderId: "rider-010",
    items: [
      { id: "item-037", name: "Jollof Spaghetti", quantity: 1, unitPrice: 1800 },
      { id: "item-038", name: "Grilled Chicken", quantity: 1, unitPrice: 2200 },
    ],
    subtotal: 4000, deliveryFee: 450, serviceFee: 150, discount: 200, total: 4400,
    paymentMethod: "card", paymentStatus: "paid",
    deliveryAddress: "7 Glover Rd, Ikoyi, Lagos",
    placedAt: daysAgo(2), confirmedAt: daysAgo(2), prepStartedAt: daysAgo(2), readyAt: daysAgo(2), pickedUpAt: daysAgo(2), deliveredAt: daysAgo(2),
    isDisputed: false,
  },
  {
    id: "aord-021", orderNumber: "#3402", status: "delivered", priority: "normal",
    customerName: "Halima Bello", customerId: "cust-019",
    vendorName: "Kilimanjaro", vendorId: "vend-004",
    riderName: "Ahmed Lawal", riderId: "rider-015",
    items: [
      { id: "item-039", name: "Catfish Pepper Soup", quantity: 1, unitPrice: 3500 },
      { id: "item-040", name: "Plantain Chips", quantity: 1, unitPrice: 800 },
    ],
    subtotal: 4300, deliveryFee: 500, serviceFee: 200, discount: 0, total: 5000,
    paymentMethod: "transfer", paymentStatus: "paid",
    deliveryAddress: "10 Maitama Sule St, Asokoro, Abuja",
    placedAt: daysAgo(3), confirmedAt: daysAgo(3), prepStartedAt: daysAgo(3), readyAt: daysAgo(3), pickedUpAt: daysAgo(3), deliveredAt: daysAgo(3),
    isDisputed: false,
  },
  {
    id: "aord-022", orderNumber: "#3401", status: "delivered", priority: "normal",
    customerName: "Chioma Okeke", customerId: "cust-001",
    vendorName: "The Place", vendorId: "vend-007",
    riderName: "Tolu Ajayi", riderId: "rider-007",
    items: [
      { id: "item-041", name: "Beans & Plantain", quantity: 1, unitPrice: 1500 },
      { id: "item-042", name: "Zobo Drink", quantity: 2, unitPrice: 400 },
    ],
    subtotal: 2300, deliveryFee: 350, serviceFee: 100, discount: 0, total: 2750,
    paymentMethod: "wallet", paymentStatus: "paid",
    deliveryAddress: "12 Admiralty Way, Lekki Phase 1, Lagos",
    placedAt: daysAgo(3), confirmedAt: daysAgo(3), prepStartedAt: daysAgo(3), readyAt: daysAgo(3), pickedUpAt: daysAgo(3), deliveredAt: daysAgo(3),
    isDisputed: false,
  },
  {
    id: "aord-023", orderNumber: "#3400", status: "delivered", priority: "normal",
    customerName: "Amara Nwosu", customerId: "cust-003",
    vendorName: "Kilimanjaro", vendorId: "vend-004",
    riderName: "Adamu Sani", riderId: "rider-003",
    items: [
      { id: "item-043", name: "Asun", quantity: 1, unitPrice: 4000 },
      { id: "item-044", name: "Fried Rice", quantity: 1, unitPrice: 2000 },
      { id: "item-045", name: "Chapman", quantity: 1, unitPrice: 1200 },
    ],
    subtotal: 7200, deliveryFee: 500, serviceFee: 250, discount: 750, total: 7200,
    paymentMethod: "card", paymentStatus: "paid",
    deliveryAddress: "3 Ozumba Mbadiwe Ave, Victoria Island, Lagos",
    placedAt: daysAgo(1), confirmedAt: daysAgo(1), prepStartedAt: daysAgo(1), readyAt: daysAgo(1), pickedUpAt: daysAgo(1), deliveredAt: daysAgo(1),
    isDisputed: false,
  },
  {
    id: "aord-024", orderNumber: "#3399", status: "delivered", priority: "normal",
    customerName: "Obinna Agu", customerId: "cust-018",
    vendorName: "Sweet Sensation", vendorId: "vend-005",
    riderName: "Chinedu Eze", riderId: "rider-005",
    items: [
      { id: "item-046", name: "Meat Pie", quantity: 2, unitPrice: 800 },
      { id: "item-047", name: "Egg Roll", quantity: 1, unitPrice: 500 },
    ],
    subtotal: 2100, deliveryFee: 350, serviceFee: 100, discount: 0, total: 2550,
    paymentMethod: "cash", paymentStatus: "paid",
    deliveryAddress: "23 Adetola St, Aguda, Surulere, Lagos",
    placedAt: daysAgo(2), confirmedAt: daysAgo(2), prepStartedAt: daysAgo(2), readyAt: daysAgo(2), pickedUpAt: daysAgo(2), deliveredAt: daysAgo(2),
    isDisputed: false,
  },
  {
    id: "aord-025", orderNumber: "#3398", status: "delivered", priority: "normal",
    customerName: "Chioma Okeke", customerId: "cust-001",
    vendorName: "Kilimanjaro", vendorId: "vend-004",
    riderName: "Ibrahim Yusuf", riderId: "rider-012",
    items: [
      { id: "item-048", name: "Mixed Grill Platter", quantity: 1, unitPrice: 5500 },
      { id: "item-049", name: "Coleslaw", quantity: 1, unitPrice: 700 },
    ],
    subtotal: 6200, deliveryFee: 500, serviceFee: 250, discount: 750, total: 6200,
    paymentMethod: "card", paymentStatus: "paid",
    deliveryAddress: "25 Adeola Odeku St, Victoria Island, Lagos",
    placedAt: daysAgo(1), confirmedAt: daysAgo(1), prepStartedAt: daysAgo(1), readyAt: daysAgo(1), pickedUpAt: daysAgo(1), deliveredAt: daysAgo(1),
    isDisputed: false,
  },
];

export const MOCK_ORDER_TIMELINES: Record<string, AdminOrderTimelineEvent[]> = {
  "aord-001": [
    { id: "evt-001", orderId: "aord-001", event: "Order Placed", description: "Customer placed order via app", timestamp: hoursAgo(1), actor: "Amara Nwosu", actorRole: "customer" },
    { id: "evt-002", orderId: "aord-001", event: "Order Confirmed", description: "Vendor accepted the order", timestamp: minutesAgo(50), actor: "Bukka Hut", actorRole: "vendor" },
    { id: "evt-003", orderId: "aord-001", event: "Preparation Started", description: "Vendor started preparing food", timestamp: minutesAgo(45), actor: "Bukka Hut", actorRole: "vendor" },
    { id: "evt-004", orderId: "aord-001", event: "Order Ready", description: "Order ready for pickup", timestamp: minutesAgo(20), actor: "Bukka Hut", actorRole: "vendor" },
    { id: "evt-005", orderId: "aord-001", event: "Rider Assigned", description: "Chinedu Eze assigned to delivery", timestamp: minutesAgo(18), actor: "System", actorRole: "system" },
    { id: "evt-006", orderId: "aord-001", event: "Picked Up", description: "Rider picked up order from vendor", timestamp: minutesAgo(15), actor: "Chinedu Eze", actorRole: "rider" },
  ],
  "aord-002": [
    { id: "evt-007", orderId: "aord-002", event: "Order Placed", description: "Customer placed order via app", timestamp: hoursAgo(3), actor: "Chioma Okeke", actorRole: "customer" },
    { id: "evt-008", orderId: "aord-002", event: "Order Confirmed", description: "Vendor accepted the order", timestamp: hoursAgo(2.8), actor: "Chicken Republic", actorRole: "vendor" },
    { id: "evt-009", orderId: "aord-002", event: "Preparation Started", description: "Vendor started preparing food", timestamp: hoursAgo(2.5), actor: "Chicken Republic", actorRole: "vendor" },
    { id: "evt-010", orderId: "aord-002", event: "Order Ready", description: "Order ready for pickup", timestamp: hoursAgo(2), actor: "Chicken Republic", actorRole: "vendor" },
    { id: "evt-011", orderId: "aord-002", event: "Picked Up", description: "Rider picked up order", timestamp: hoursAgo(1.8), actor: "Adamu Sani", actorRole: "rider" },
    { id: "evt-012", orderId: "aord-002", event: "Delivered", description: "Order delivered to customer", timestamp: hoursAgo(1.5), actor: "Adamu Sani", actorRole: "rider" },
    { id: "evt-013", orderId: "aord-002", event: "Dispute Filed", description: "Customer reported duplicate payment", timestamp: hoursAgo(1.2), actor: "Chioma Okeke", actorRole: "customer" },
    { id: "evt-014", orderId: "aord-002", event: "Admin Review", description: "Investigating duplicate charge with Paystack", timestamp: hoursAgo(1), actor: "Adebayo Ogunlesi", actorRole: "admin" },
  ],
  "aord-005": [
    { id: "evt-015", orderId: "aord-005", event: "Order Placed", description: "Customer placed order via app", timestamp: minutesAgo(45), actor: "Kemi Oladipo", actorRole: "customer" },
    { id: "evt-016", orderId: "aord-005", event: "Order Confirmed", description: "Vendor accepted the order", timestamp: minutesAgo(40), actor: "Kilimanjaro", actorRole: "vendor" },
    { id: "evt-017", orderId: "aord-005", event: "Preparation Started", description: "Vendor started preparing food", timestamp: minutesAgo(35), actor: "Kilimanjaro", actorRole: "vendor" },
    { id: "evt-018", orderId: "aord-005", event: "Escalated to Urgent", description: "Customer waiting 45+ min — escalated by system", timestamp: minutesAgo(5), actor: "System", actorRole: "system" },
  ],
  "aord-008": [
    { id: "evt-019", orderId: "aord-008", event: "Order Placed", description: "Customer placed order via app", timestamp: hoursAgo(8), actor: "Aisha Mohammed", actorRole: "customer" },
    { id: "evt-020", orderId: "aord-008", event: "Order Confirmed", description: "Vendor accepted the order", timestamp: hoursAgo(7.8), actor: "The Place", actorRole: "vendor" },
    { id: "evt-021", orderId: "aord-008", event: "Delivered", description: "Order delivered to customer", timestamp: hoursAgo(6.5), actor: "Musa Bello", actorRole: "rider" },
    { id: "evt-022", orderId: "aord-008", event: "Dispute Filed", description: "Customer reported wrong items delivered", timestamp: hoursAgo(6), actor: "Aisha Mohammed", actorRole: "customer" },
    { id: "evt-023", orderId: "aord-008", event: "Admin Investigating", description: "Contacting vendor to confirm item mix-up", timestamp: hoursAgo(5.5), actor: "Adebayo Ogunlesi", actorRole: "admin" },
  ],
};

export const MOCK_ORDER_DISPUTES: OrderDispute[] = [
  {
    id: "disp-001",
    orderId: "aord-002",
    status: "investigating",
    reason: "Duplicate payment",
    description: "Customer was charged twice for the same order. Paystack transaction logs show two successful debits.",
    filedBy: "Chioma Okeke",
    filedAt: hoursAgo(1.2),
    adminAssignee: "Adebayo Ogunlesi",
  },
  {
    id: "disp-002",
    orderId: "aord-008",
    status: "open",
    reason: "Wrong items delivered",
    description: "Customer ordered Amala & Ewedu but received Amala & Gbegiri. Vendor confirmed the mix-up.",
    filedBy: "Aisha Mohammed",
    filedAt: hoursAgo(6),
    adminAssignee: "Adebayo Ogunlesi",
  },
  {
    id: "disp-003",
    orderId: "aord-013",
    status: "resolved",
    reason: "Delivery failure",
    description: "Rider marked as delivered but never arrived. GPS logs show rider did not reach delivery address.",
    filedBy: "Solomon Adegoke",
    filedAt: daysAgo(1),
    resolvedAt: daysAgo(1),
    resolution: "Full refund issued. Rider given warning.",
    adminAssignee: "Adebayo Ogunlesi",
  },
  {
    id: "disp-004",
    orderId: "aord-019",
    status: "resolved",
    reason: "Customer cancellation",
    description: "Customer requested cancellation before vendor started preparing. Full refund processed.",
    filedBy: "Yusuf Ibrahim",
    filedAt: daysAgo(2),
    resolvedAt: daysAgo(2),
    resolution: "Refund processed automatically — order not yet in preparation.",
  },
];
