import type { AdminVendor, VendorApplication } from "@/types";

const now = new Date();
function daysAgo(days: number): string {
  return new Date(now.getTime() - days * 86400000).toISOString();
}
function hoursAgo(hours: number): string {
  return new Date(now.getTime() - hours * 3600000).toISOString();
}

export const MOCK_ADMIN_VENDORS: AdminVendor[] = [
  {
    id: "vend-001", name: "Bukka Hut", ownerName: "Adebola Adeyemi",
    email: "info@bukkahut.com", phone: "+234 810 111 2222",
    address: "Plot 23, Admiralty Way, Lekki Phase 1, Lagos",
    cuisineTypes: ["Nigerian", "Continental"],
    status: "active", onboardingStatus: "approved",
    joinedAt: "2025-01-15T10:00:00Z", totalOrders: 2840, totalRevenue: 14200000,
    rating: 4.6, totalReviews: 1820, commissionRate: 15,
    isOpen: true, lastActiveAt: hoursAgo(0.5), performanceScore: 92,
    avgPrepTime: 22, cancellationRate: 2.1, currentBalance: 1250000, totalPaid: 12950000,
  },
  {
    id: "vend-002", name: "Chicken Republic", ownerName: "Funmilayo Oni",
    email: "manager@chickenrepublic.ng", phone: "+234 802 222 3333",
    address: "15 Allen Avenue, Ikeja, Lagos",
    cuisineTypes: ["Fast Food", "Nigerian"],
    status: "active", onboardingStatus: "approved",
    joinedAt: "2025-02-01T09:00:00Z", totalOrders: 3560, totalRevenue: 17800000,
    rating: 4.4, totalReviews: 2340, commissionRate: 12,
    isOpen: true, lastActiveAt: hoursAgo(1), performanceScore: 88,
    avgPrepTime: 18, cancellationRate: 3.2, currentBalance: 980000, totalPaid: 16820000,
  },
  {
    id: "vend-003", name: "Domino's Pizza", ownerName: "Chidi Amaechi",
    email: "lagos@dominos.ng", phone: "+234 815 333 4444",
    address: "5 Adeola Odeku Street, Victoria Island, Lagos",
    cuisineTypes: ["Pizza", "Fast Food"],
    status: "active", onboardingStatus: "approved",
    joinedAt: "2025-01-20T11:00:00Z", totalOrders: 2120, totalRevenue: 21200000,
    rating: 4.5, totalReviews: 1560, commissionRate: 10,
    isOpen: true, lastActiveAt: hoursAgo(2), performanceScore: 90,
    avgPrepTime: 25, cancellationRate: 1.8, currentBalance: 1540000, totalPaid: 19660000,
  },
  {
    id: "vend-004", name: "Kilimanjaro", ownerName: "Muhammed Abubakar",
    email: "ops@kilimanjaro.ng", phone: "+234 806 444 5555",
    address: "42 Awolowo Road, Ikoyi, Lagos",
    cuisineTypes: ["Nigerian", "Grill", "Continental"],
    status: "active", onboardingStatus: "approved",
    joinedAt: "2025-03-10T10:00:00Z", totalOrders: 1960, totalRevenue: 11760000,
    rating: 4.7, totalReviews: 1280, commissionRate: 15,
    isOpen: true, lastActiveAt: hoursAgo(1.5), performanceScore: 95,
    avgPrepTime: 28, cancellationRate: 1.2, currentBalance: 880000, totalPaid: 10880000,
  },
  {
    id: "vend-005", name: "Sweet Sensation", ownerName: "Ngozi Obi",
    email: "contact@sweetsensation.ng", phone: "+234 811 555 6666",
    address: "8 Ogunlana Drive, Surulere, Lagos",
    cuisineTypes: ["Fast Food", "Bakery"],
    status: "active", onboardingStatus: "approved",
    joinedAt: "2025-04-01T14:00:00Z", totalOrders: 1480, totalRevenue: 5920000,
    rating: 4.2, totalReviews: 960, commissionRate: 15,
    isOpen: false, lastActiveAt: hoursAgo(8), performanceScore: 78,
    avgPrepTime: 15, cancellationRate: 4.5, currentBalance: 420000, totalPaid: 5500000,
  },
  {
    id: "vend-006", name: "Tantalizers", ownerName: "Emeka Eze",
    email: "info@tantalizers.com", phone: "+234 803 666 7777",
    address: "12 Herbert Macaulay Way, Yaba, Lagos",
    cuisineTypes: ["Fast Food", "Nigerian"],
    status: "active", onboardingStatus: "approved",
    joinedAt: "2025-03-22T09:00:00Z", totalOrders: 1340, totalRevenue: 6700000,
    rating: 4.3, totalReviews: 880, commissionRate: 15,
    isOpen: true, lastActiveAt: hoursAgo(3), performanceScore: 82,
    avgPrepTime: 20, cancellationRate: 3.8, currentBalance: 560000, totalPaid: 6140000,
  },
  {
    id: "vend-007", name: "The Place", ownerName: "Oluwakemi Johnson",
    email: "manager@theplace.ng", phone: "+234 817 777 8888",
    address: "25 Isaac John Street, Ikeja GRA, Lagos",
    cuisineTypes: ["Nigerian", "Continental"],
    status: "active", onboardingStatus: "approved",
    joinedAt: "2025-02-14T12:00:00Z", totalOrders: 2240, totalRevenue: 11200000,
    rating: 4.5, totalReviews: 1440, commissionRate: 12,
    isOpen: true, lastActiveAt: hoursAgo(2), performanceScore: 87,
    avgPrepTime: 24, cancellationRate: 2.8, currentBalance: 720000, totalPaid: 10480000,
  },
  {
    id: "vend-008", name: "KFC Nigeria", ownerName: "Yetunde Bakare",
    email: "lagos.ops@kfc.ng", phone: "+234 808 888 9999",
    address: "3 Adeola Hopewell Street, Victoria Island, Lagos",
    cuisineTypes: ["Fast Food", "Chicken"],
    status: "suspended", onboardingStatus: "approved",
    joinedAt: "2025-05-01T10:00:00Z", totalOrders: 890, totalRevenue: 7120000,
    rating: 3.8, totalReviews: 620, commissionRate: 10,
    isOpen: false, lastActiveAt: daysAgo(3), performanceScore: 62,
    avgPrepTime: 30, cancellationRate: 8.2, currentBalance: 340000, totalPaid: 6780000,
  },
  {
    id: "vend-009", name: "Tasty Bites Lagos", ownerName: "Ibrahim Musa",
    email: "tastybites@gmail.com", phone: "+234 814 999 0000",
    address: "7 Bode Thomas Street, Surulere, Lagos",
    cuisineTypes: ["Nigerian", "Snacks"],
    status: "active", onboardingStatus: "approved",
    joinedAt: "2025-06-15T11:00:00Z", totalOrders: 420, totalRevenue: 1680000,
    rating: 4.1, totalReviews: 280, commissionRate: 18,
    isOpen: true, lastActiveAt: hoursAgo(4), performanceScore: 76,
    avgPrepTime: 20, cancellationRate: 3.5, currentBalance: 180000, totalPaid: 1500000,
  },
  {
    id: "vend-010", name: "Lagos Grills & Co", ownerName: "Adaeze Umeh",
    email: "lagosgrills@outlook.com", phone: "+234 805 000 1111",
    address: "19 Akin Adesola Street, Victoria Island, Lagos",
    cuisineTypes: ["Grill", "BBQ", "Nigerian"],
    status: "active", onboardingStatus: "approved",
    joinedAt: "2025-07-01T09:00:00Z", totalOrders: 280, totalRevenue: 1960000,
    rating: 4.4, totalReviews: 180, commissionRate: 15,
    isOpen: true, lastActiveAt: hoursAgo(5), performanceScore: 84,
    avgPrepTime: 30, cancellationRate: 2.0, currentBalance: 220000, totalPaid: 1740000,
  },
  {
    id: "vend-011", name: "Mama Cass", ownerName: "Cassandra Okafor",
    email: "mamacass@gmail.com", phone: "+234 816 111 2222",
    address: "10 Adeniran Ogunsanya St, Surulere, Lagos",
    cuisineTypes: ["Nigerian", "Homestyle"],
    status: "active", onboardingStatus: "approved",
    joinedAt: "2025-05-20T14:00:00Z", totalOrders: 560, totalRevenue: 2240000,
    rating: 4.6, totalReviews: 380, commissionRate: 18,
    isOpen: true, lastActiveAt: hoursAgo(2), performanceScore: 91,
    avgPrepTime: 25, cancellationRate: 1.5, currentBalance: 260000, totalPaid: 1980000,
  },
  {
    id: "vend-012", name: "Café Neo", ownerName: "Tomiwa Adebayo",
    email: "partner@cafeneo.com", phone: "+234 809 222 3333",
    address: "1 Ozumba Mbadiwe Avenue, Victoria Island, Lagos",
    cuisineTypes: ["Coffee", "Pastry", "Light Meals"],
    status: "active", onboardingStatus: "approved",
    joinedAt: "2025-04-15T08:00:00Z", totalOrders: 780, totalRevenue: 3120000,
    rating: 4.3, totalReviews: 520, commissionRate: 15,
    isOpen: true, lastActiveAt: hoursAgo(1), performanceScore: 85,
    avgPrepTime: 12, cancellationRate: 2.2, currentBalance: 310000, totalPaid: 2810000,
  },
  {
    id: "vend-013", name: "Quick Eats", ownerName: "Bayo Dada",
    email: "quickeats.lag@gmail.com", phone: "+234 801 333 4444",
    address: "33 Toyin Street, Ikeja, Lagos",
    cuisineTypes: ["Fast Food", "Snacks"],
    status: "suspended", onboardingStatus: "approved",
    joinedAt: "2025-06-01T10:00:00Z", totalOrders: 180, totalRevenue: 540000,
    rating: 3.2, totalReviews: 120, commissionRate: 20,
    isOpen: false, lastActiveAt: daysAgo(7), performanceScore: 45,
    avgPrepTime: 35, cancellationRate: 12.5, currentBalance: 45000, totalPaid: 495000,
  },
  {
    id: "vend-014", name: "Nkoyo's Kitchen", ownerName: "Nkoyo Essien",
    email: "nkoyos@yahoo.com", phone: "+234 818 444 5555",
    address: "6 Aba Johnson Crescent, Lekki Phase 1, Lagos",
    cuisineTypes: ["Nigerian", "Calabar"],
    status: "inactive", onboardingStatus: "approved",
    joinedAt: "2025-07-10T12:00:00Z", totalOrders: 45, totalRevenue: 225000,
    rating: 4.0, totalReviews: 30, commissionRate: 18,
    isOpen: false, lastActiveAt: daysAgo(21), performanceScore: 55,
    avgPrepTime: 28, cancellationRate: 6.7, currentBalance: 32000, totalPaid: 193000,
  },
  {
    id: "vend-015", name: "Peppersoup Junction", ownerName: "Chukwuma Nwoye",
    email: "psjunction@gmail.com", phone: "+234 807 555 6666",
    address: "14 Ligali Ayorinde St, Victoria Island, Lagos",
    cuisineTypes: ["Nigerian", "Seafood"],
    status: "pending_approval", onboardingStatus: "documents_under_review",
    joinedAt: daysAgo(5), totalOrders: 0, totalRevenue: 0,
    rating: 0, totalReviews: 0, commissionRate: 15,
    isOpen: false, lastActiveAt: daysAgo(5), performanceScore: 0,
    avgPrepTime: 0, cancellationRate: 0, currentBalance: 0, totalPaid: 0,
  },
];

export const MOCK_VENDOR_APPLICATIONS: VendorApplication[] = [
  {
    id: "app-001",
    vendorName: "Bukka Hut Express",
    ownerName: "Adebola Adeyemi Jr.",
    email: "express@bukkahut.com",
    phone: "+234 810 222 3333",
    address: "45 Ajose Adeogun St, Victoria Island, Lagos",
    cuisineTypes: ["Nigerian", "Fast Food"],
    status: "application_submitted",
    submittedAt: daysAgo(2),
    documents: [
      { id: "doc-001", name: "CAC Certificate", type: "business_registration", status: "pending", uploadedAt: daysAgo(2) },
      { id: "doc-002", name: "NAFDAC License", type: "food_license", status: "pending", uploadedAt: daysAgo(2) },
      { id: "doc-003", name: "Owner ID Card", type: "id_card", status: "pending", uploadedAt: daysAgo(2) },
    ],
  },
  {
    id: "app-002",
    vendorName: "Mama Put Deluxe",
    ownerName: "Aderonke Williams",
    email: "mamaputdeluxe@gmail.com",
    phone: "+234 813 333 4444",
    address: "8 Opebi Road, Ikeja, Lagos",
    cuisineTypes: ["Nigerian", "Homestyle"],
    status: "documents_under_review",
    submittedAt: daysAgo(5),
    documents: [
      { id: "doc-004", name: "Business Registration", type: "business_registration", status: "approved", uploadedAt: daysAgo(5) },
      { id: "doc-005", name: "Food Handlers License", type: "food_license", status: "pending", uploadedAt: daysAgo(5) },
      { id: "doc-006", name: "National ID", type: "id_card", status: "approved", uploadedAt: daysAgo(5) },
      { id: "doc-007", name: "Bank Statement", type: "bank_statement", status: "pending", uploadedAt: daysAgo(4) },
    ],
  },
  {
    id: "app-003",
    vendorName: "Peppersoup Junction",
    ownerName: "Chukwuma Nwoye",
    email: "psjunction@gmail.com",
    phone: "+234 807 555 6666",
    address: "14 Ligali Ayorinde St, Victoria Island, Lagos",
    cuisineTypes: ["Nigerian", "Seafood"],
    status: "documents_under_review",
    submittedAt: daysAgo(5),
    documents: [
      { id: "doc-008", name: "CAC Certificate", type: "business_registration", status: "approved", uploadedAt: daysAgo(5) },
      { id: "doc-009", name: "Lagos State Food License", type: "food_license", status: "approved", uploadedAt: daysAgo(5) },
      { id: "doc-010", name: "Passport Photograph", type: "id_card", status: "approved", uploadedAt: daysAgo(5) },
    ],
  },
  {
    id: "app-004",
    vendorName: "Grill Master NG",
    ownerName: "Segun Ojo",
    email: "grillmaster@outlook.com",
    phone: "+234 804 666 7777",
    address: "22 Awolowo Road, Falomo, Ikoyi, Lagos",
    cuisineTypes: ["Grill", "BBQ"],
    status: "site_inspection_pending",
    submittedAt: daysAgo(10),
    reviewedAt: daysAgo(3),
    reviewedBy: "Adebayo Ogunlesi",
    documents: [
      { id: "doc-011", name: "CAC Certificate", type: "business_registration", status: "approved", uploadedAt: daysAgo(10) },
      { id: "doc-012", name: "NAFDAC License", type: "food_license", status: "approved", uploadedAt: daysAgo(10) },
      { id: "doc-013", name: "Driver's License", type: "id_card", status: "approved", uploadedAt: daysAgo(10) },
    ],
  },
  {
    id: "app-005",
    vendorName: "Noodle Box Lagos",
    ownerName: "Chen Wei",
    email: "noodlebox.lag@gmail.com",
    phone: "+234 819 777 8888",
    address: "3 Adeola Hopewell, Victoria Island, Lagos",
    cuisineTypes: ["Chinese", "Asian"],
    status: "rejected",
    submittedAt: daysAgo(14),
    reviewedAt: daysAgo(7),
    reviewedBy: "Adebayo Ogunlesi",
    rejectionReason: "Business registration expired. Food handling license not provided.",
    documents: [
      { id: "doc-014", name: "Expired CAC Certificate", type: "business_registration", status: "rejected", uploadedAt: daysAgo(14) },
      { id: "doc-015", name: "Owner ID", type: "id_card", status: "approved", uploadedAt: daysAgo(14) },
    ],
  },
  {
    id: "app-006",
    vendorName: "Smokin' Joe's BBQ",
    ownerName: "Joseph Akinwale",
    email: "smokinjoes@gmail.com",
    phone: "+234 812 888 9999",
    address: "17 Lekki-Epe Expressway, Ajah, Lagos",
    cuisineTypes: ["BBQ", "American"],
    status: "application_submitted",
    submittedAt: daysAgo(1),
    documents: [
      { id: "doc-016", name: "CAC Certificate", type: "business_registration", status: "pending", uploadedAt: daysAgo(1) },
      { id: "doc-017", name: "Food License", type: "food_license", status: "pending", uploadedAt: daysAgo(1) },
      { id: "doc-018", name: "NIN Slip", type: "id_card", status: "pending", uploadedAt: daysAgo(1) },
      { id: "doc-019", name: "Bank Statement", type: "bank_statement", status: "pending", uploadedAt: daysAgo(1) },
    ],
  },
];
