import type { VendorOrder, ActivityEvent } from "@/types";

const now = new Date();
function minutesAgo(minutes: number): string {
  return new Date(now.getTime() - minutes * 60000).toISOString();
}
function hoursAgo(hours: number): string {
  return new Date(now.getTime() - hours * 3600000).toISOString();
}

export const MOCK_VENDOR_ORDERS: VendorOrder[] = [
  // --- NEW (3) ---
  {
    id: "VO-001",
    orderNumber: "#1001",
    status: "new",
    customerName: "Chidi Eze",
    customerPhone: "+234 801 ***-**34",
    items: [
      { id: "i1", name: "Jollof Rice", quantity: 2, unitPrice: 2500, modifiers: ["Extra Chicken"] },
      { id: "i2", name: "Chapman", quantity: 2, unitPrice: 1200 },
    ],
    subtotal: 7400,
    deliveryFee: 500,
    serviceFee: 370,
    total: 8270,
    specialInstructions: "Please make the rice extra spicy",
    placedAt: minutesAgo(2),
    estimatedPrepTime: 20,
    deliveryAddress: "12 Admiralty Way, Lekki Phase 1, Lagos",
    paymentMethod: "card",
  },
  {
    id: "VO-002",
    orderNumber: "#1002",
    status: "new",
    customerName: "Amina Bello",
    customerPhone: "+234 803 ***-**67",
    items: [
      { id: "i3", name: "Pounded Yam & Egusi", quantity: 1, unitPrice: 3500, modifiers: ["Beef", "Stockfish"] },
      { id: "i4", name: "Fried Plantain", quantity: 1, unitPrice: 800 },
      { id: "i5", name: "Zobo Drink", quantity: 1, unitPrice: 600 },
    ],
    subtotal: 4900,
    deliveryFee: 500,
    serviceFee: 245,
    total: 5645,
    placedAt: minutesAgo(5),
    estimatedPrepTime: 25,
    deliveryAddress: "5 Ozumba Mbadiwe Ave, Victoria Island, Lagos",
    paymentMethod: "transfer",
  },
  {
    id: "VO-003",
    orderNumber: "#1003",
    status: "new",
    customerName: "Tunde Akinola",
    customerPhone: "+234 805 ***-**12",
    items: [
      { id: "i6", name: "Suya Platter", quantity: 1, unitPrice: 4500 },
      { id: "i7", name: "Pepper Soup", quantity: 1, unitPrice: 2800, modifiers: ["Goat Meat"] },
    ],
    subtotal: 7300,
    deliveryFee: 500,
    serviceFee: 365,
    total: 8165,
    specialInstructions: "No onions on the suya please",
    placedAt: minutesAgo(8),
    estimatedPrepTime: 30,
    deliveryAddress: "22 Akin Adesola St, Victoria Island, Lagos",
    paymentMethod: "wallet",
  },

  // --- PREPARING (3) ---
  {
    id: "VO-004",
    orderNumber: "#1004",
    status: "preparing",
    customerName: "Ngozi Okonkwo",
    customerPhone: "+234 802 ***-**89",
    items: [
      { id: "i8", name: "Fried Rice & Chicken", quantity: 2, unitPrice: 3000 },
      { id: "i9", name: "Moi Moi", quantity: 2, unitPrice: 500 },
    ],
    subtotal: 7000,
    deliveryFee: 500,
    serviceFee: 350,
    total: 7850,
    placedAt: minutesAgo(15),
    acceptedAt: minutesAgo(12),
    prepStartedAt: minutesAgo(12),
    estimatedPrepTime: 20,
    deliveryAddress: "8 Adetokunbo Ademola St, Wuse 2, Abuja",
    paymentMethod: "card",
  },
  {
    id: "VO-005",
    orderNumber: "#1005",
    status: "preparing",
    customerName: "Yemi Adeyemi",
    customerPhone: "+234 806 ***-**45",
    items: [
      { id: "i10", name: "Ofada Rice & Sauce", quantity: 1, unitPrice: 3200, modifiers: ["Extra Assorted Meat"] },
    ],
    subtotal: 3200,
    deliveryFee: 500,
    serviceFee: 160,
    total: 3860,
    specialInstructions: "Extra sauce on the side",
    placedAt: minutesAgo(20),
    acceptedAt: minutesAgo(17),
    prepStartedAt: minutesAgo(17),
    estimatedPrepTime: 15,
    deliveryAddress: "15 Allen Avenue, Ikeja, Lagos",
    paymentMethod: "cash",
  },
  {
    id: "VO-006",
    orderNumber: "#1006",
    status: "preparing",
    customerName: "Emeka Nwosu",
    customerPhone: "+234 807 ***-**23",
    items: [
      { id: "i11", name: "Amala & Ewedu", quantity: 1, unitPrice: 2500, modifiers: ["Gbegiri", "Assorted Meat"] },
      { id: "i12", name: "Fried Plantain", quantity: 2, unitPrice: 800 },
      { id: "i13", name: "Water", quantity: 2, unitPrice: 200 },
    ],
    subtotal: 4500,
    deliveryFee: 500,
    serviceFee: 225,
    total: 5225,
    placedAt: minutesAgo(25),
    acceptedAt: minutesAgo(22),
    prepStartedAt: minutesAgo(22),
    estimatedPrepTime: 18,
    deliveryAddress: "3 Bode Thomas St, Surulere, Lagos",
    paymentMethod: "transfer",
  },

  // --- READY (2) ---
  {
    id: "VO-007",
    orderNumber: "#1007",
    status: "ready",
    customerName: "Funke Oladipo",
    customerPhone: "+234 808 ***-**56",
    items: [
      { id: "i14", name: "Chicken & Chips", quantity: 1, unitPrice: 3500 },
      { id: "i15", name: "Coleslaw", quantity: 1, unitPrice: 500 },
    ],
    subtotal: 4000,
    deliveryFee: 500,
    serviceFee: 200,
    total: 4700,
    placedAt: minutesAgo(35),
    acceptedAt: minutesAgo(32),
    prepStartedAt: minutesAgo(32),
    readyAt: minutesAgo(5),
    estimatedPrepTime: 15,
    deliveryAddress: "10 Awolowo Rd, Ikoyi, Lagos",
    paymentMethod: "card",
  },
  {
    id: "VO-008",
    orderNumber: "#1008",
    status: "ready",
    customerName: "Ibrahim Musa",
    customerPhone: "+234 809 ***-**78",
    items: [
      { id: "i16", name: "Sharwarma (Large)", quantity: 2, unitPrice: 3000 },
      { id: "i17", name: "Smoothie", quantity: 2, unitPrice: 1500 },
    ],
    subtotal: 9000,
    deliveryFee: 500,
    serviceFee: 450,
    total: 9950,
    placedAt: minutesAgo(40),
    acceptedAt: minutesAgo(37),
    prepStartedAt: minutesAgo(37),
    readyAt: minutesAgo(8),
    estimatedPrepTime: 20,
    deliveryAddress: "7 Adeola Odeku St, Victoria Island, Lagos",
    paymentMethod: "wallet",
  },

  // --- COMPLETED (3) ---
  {
    id: "VO-009",
    orderNumber: "#1009",
    status: "completed",
    customerName: "Adaeze Okoro",
    customerPhone: "+234 810 ***-**90",
    items: [
      { id: "i18", name: "Jollof Rice", quantity: 3, unitPrice: 2500 },
      { id: "i19", name: "Grilled Fish", quantity: 1, unitPrice: 4500 },
    ],
    subtotal: 12000,
    deliveryFee: 500,
    serviceFee: 600,
    total: 13100,
    placedAt: hoursAgo(2),
    acceptedAt: hoursAgo(1.9),
    prepStartedAt: hoursAgo(1.9),
    readyAt: hoursAgo(1.5),
    completedAt: hoursAgo(1),
    estimatedPrepTime: 25,
    deliveryAddress: "18 Kofo Abayomi Ave, Victoria Island, Lagos",
    paymentMethod: "card",
  },
  {
    id: "VO-010",
    orderNumber: "#1010",
    status: "completed",
    customerName: "Segun Bakare",
    customerPhone: "+234 811 ***-**01",
    items: [
      { id: "i20", name: "Nkwobi", quantity: 1, unitPrice: 5000 },
      { id: "i21", name: "Palm Wine", quantity: 2, unitPrice: 1000 },
    ],
    subtotal: 7000,
    deliveryFee: 500,
    serviceFee: 350,
    total: 7850,
    placedAt: hoursAgo(3),
    acceptedAt: hoursAgo(2.9),
    prepStartedAt: hoursAgo(2.9),
    readyAt: hoursAgo(2.5),
    completedAt: hoursAgo(2),
    estimatedPrepTime: 20,
    deliveryAddress: "25 Ajose Adeogun St, Victoria Island, Lagos",
    paymentMethod: "transfer",
  },
  {
    id: "VO-011",
    orderNumber: "#1011",
    status: "completed",
    customerName: "Halima Abdullahi",
    customerPhone: "+234 812 ***-**34",
    items: [
      { id: "i22", name: "Fried Rice & Chicken", quantity: 1, unitPrice: 3000 },
    ],
    subtotal: 3000,
    deliveryFee: 500,
    serviceFee: 150,
    total: 3650,
    placedAt: hoursAgo(4),
    acceptedAt: hoursAgo(3.9),
    prepStartedAt: hoursAgo(3.9),
    readyAt: hoursAgo(3.5),
    completedAt: hoursAgo(3),
    estimatedPrepTime: 15,
    deliveryAddress: "2 Sanusi Fafunwa St, Victoria Island, Lagos",
    paymentMethod: "cash",
  },

  // --- CANCELLED (1) ---
  {
    id: "VO-012",
    orderNumber: "#1012",
    status: "cancelled",
    customerName: "Kola Taiwo",
    customerPhone: "+234 813 ***-**56",
    items: [
      { id: "i23", name: "Pepper Soup", quantity: 1, unitPrice: 2800, modifiers: ["Catfish"] },
      { id: "i24", name: "Garri & Groundnut", quantity: 1, unitPrice: 500 },
    ],
    subtotal: 3300,
    deliveryFee: 500,
    serviceFee: 165,
    total: 3965,
    placedAt: hoursAgo(1),
    cancelledAt: minutesAgo(45),
    cancelReason: "Customer requested cancellation",
    estimatedPrepTime: 20,
    deliveryAddress: "30 Toyin St, Ikeja, Lagos",
    paymentMethod: "card",
  },
];

export const MOCK_ACTIVITY_FEED: ActivityEvent[] = [
  { id: "act-1", type: "new_order", message: "New order #1001 from Chidi Eze", timestamp: minutesAgo(2), orderId: "VO-001" },
  { id: "act-2", type: "new_order", message: "New order #1002 from Amina Bello", timestamp: minutesAgo(5), orderId: "VO-002" },
  { id: "act-3", type: "order_ready", message: "Order #1007 marked as ready", timestamp: minutesAgo(5), orderId: "VO-007" },
  { id: "act-4", type: "new_order", message: "New order #1003 from Tunde Akinola", timestamp: minutesAgo(8), orderId: "VO-003" },
  { id: "act-5", type: "order_ready", message: "Order #1008 marked as ready", timestamp: minutesAgo(8), orderId: "VO-008" },
  { id: "act-6", type: "order_cancelled", message: "Order #1012 was cancelled", timestamp: minutesAgo(45), orderId: "VO-012" },
  { id: "act-7", type: "order_completed", message: "Order #1009 delivered successfully", timestamp: hoursAgo(1), orderId: "VO-009" },
  { id: "act-8", type: "order_completed", message: "Order #1010 delivered successfully", timestamp: hoursAgo(2), orderId: "VO-010" },
  { id: "act-9", type: "payout_received", message: "Weekly payout of ₦185,250 processed", timestamp: hoursAgo(5) },
  { id: "act-10", type: "item_out_of_stock", message: "Palm Wine marked as out of stock", timestamp: hoursAgo(6) },
];
